title: JB2A - Knowledge Base
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://Jules-Bens-Aa.github.io/jb2a.github.io

aux_links:
  Template Repository: https://github.com/Jules-Bens-Aa/jb2a.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
